insert into public.prompts
  (id, slug, title, description, category, prompt_text, tags, is_featured, published_at)
values
  ('10000000-0000-4000-8000-000000000001', 'turn-uncertainty-into-a-decision', 'Turn uncertainty into a decision', 'Map the choice, the tradeoffs, and the smallest honest next move.', 'think', 'Help me examine this decision without rushing to certainty. Name the real choice, the tradeoffs I may be avoiding, what each path protects, and the smallest honest next move I can make today.', array['decisions','clarity'], true, now()),
  ('10000000-0000-4000-8000-000000000002', 'test-an-idea-simply', 'What is the simplest way to test this idea?', 'Turn a large possibility into one small, useful experiment.', 'create', 'Act as a rigorous but encouraging product strategist. Help me identify the riskiest assumption in this idea and design the smallest real-world test I can run this week. Keep the test inexpensive, observable, and honest.', array['experiments','founders'], true, now()),
  ('10000000-0000-4000-8000-000000000003', 'design-a-morning-ritual', 'Design a meaningful ritual for the start of my day', 'Build a short practice around attention, energy, and what matters.', 'reflect', 'Design a morning ritual that fits my real life. Ask what I want to protect, how much time I actually have, and what usually derails me. Then propose a simple sequence with a two-minute fallback version.', array['ritual','attention'], false, now()),
  ('10000000-0000-4000-8000-000000000004', 'distill-research-into-principles', 'Distill this research into principles I can use', 'Move from information overload to durable, testable understanding.', 'work', 'Read the material I provide and extract the smallest set of durable principles that explain most of it. For each principle, include what it means, when it is useful, where it can fail, and one concrete application.', array['research','learning'], true, now()),
  ('10000000-0000-4000-8000-000000000005', 'what-am-i-avoiding', 'What am I avoiding by staying busy?', 'Use your calendar and commitments as evidence, not as a verdict.', 'reflect', 'Help me examine whether busyness is protecting me from a harder task, feeling, or decision. Ask one question at a time. Be candid without being theatrical, and finish with one gentle action that creates space.', array['reflection','focus'], false, now()),
  ('10000000-0000-4000-8000-000000000006', 'write-the-brief-you-wish-you-had', 'Write the brief I wish I had', 'Create alignment before the work becomes expensive.', 'work', 'Turn my rough project notes into a clear working brief. Include the outcome, audience, non-goals, constraints, open questions, decisions already made, measures of success, and the next three actions.', array['planning','teams'], true, now()),
  ('10000000-0000-4000-8000-000000000007', 'money-not-the-goal', 'What would this look like if money were not the goal?', 'Separate the thing you value from the business model around it.', 'think', 'Help me imagine this project if money were not the primary goal, without pretending money is irrelevant. Identify the human value, the minimum sustainable economics, and what I would choose differently.', array['values','business'], false, now()),
  ('10000000-0000-4000-8000-000000000008', 'who-can-i-help-that-cannot-repay-me', 'Who can I help that cannot repay me?', 'Find a concrete act of generosity that respects the other person.', 'reflect', 'Help me identify someone or a community I can support without expecting access, status, or repayment. Keep the action specific, dignified, and within my actual capacity.', array['community','generosity'], false, now()),
  ('10000000-0000-4000-8000-000000000009', 'six-month-focus', 'If I had six months, what would I focus on?', 'Choose a season of work with a clear finish line.', 'think', 'Help me choose one six-month focus. Compare my options by meaning, leverage, reversibility, energy, and who benefits. Then propose a finish line, what to pause, and a first-week plan.', array['focus','strategy'], true, now()),
  ('10000000-0000-4000-8000-000000000010', 'make-this-more-generous', 'What would make this more generous?', 'Improve an offer by increasing real value, clarity, or agency.', 'create', 'Review the offer, product, or message I provide. Suggest ways to make it more generous without manipulation: clearer expectations, greater user agency, useful free value, fairer risk sharing, and more respectful defaults.', array['product','trust'], false, now()),
  ('10000000-0000-4000-8000-000000000011', 'assumptions-holding-me-back', 'Which assumptions are holding me back?', 'Name the invisible rules shaping your choices, then test them.', 'think', 'Help me uncover assumptions I am treating as facts. Sort them into evidence-backed constraints, inherited beliefs, fears, and unknowns. Design one respectful test for the assumption with the highest cost.', array['beliefs','experiments'], false, now()),
  ('10000000-0000-4000-8000-000000000012', 'explain-it-to-a-smart-outsider', 'Explain this to a smart outsider', 'Find the plain-language shape of a complex idea.', 'work', 'Explain the material I provide to an intelligent person outside the field. Preserve the important nuance, define unavoidable terms, use one strong analogy, and name what the explanation leaves out.', array['writing','clarity'], false, now()),
  ('10000000-0000-4000-8000-000000000013', 'pre-mortem-without-pessimism', 'Run a pre-mortem without killing the idea', 'Surface preventable failure while protecting creative momentum.', 'work', 'Imagine this project failed one year from now. Identify the five most plausible causes, early warning signs, and low-cost mitigations. Distinguish fatal risks from discomfort and ordinary uncertainty.', array['risk','planning'], false, now()),
  ('10000000-0000-4000-8000-000000000014', 'find-the-human-story', 'Find the human story inside these facts', 'Turn raw information into a truthful narrative people can feel.', 'create', 'Find the strongest truthful human story in the facts I provide. Identify the person, tension, change, and stakes. Do not invent details or manufacture sentiment. Draft a clear narrative spine.', array['storytelling','writing'], false, now()),
  ('10000000-0000-4000-8000-000000000015', 'build-a-personal-advisory-council', 'Build a personal advisory council', 'Examine one question through distinct, useful schools of thought.', 'think', 'Create a small advisory council for my question using distinct perspectives such as Socratic inquiry, systems thinking, practical operations, ethics, and long-term stewardship. Let each perspective challenge the others before synthesizing.', array['great-thinkers','decisions'], true, now()),
  ('10000000-0000-4000-8000-000000000016', 'make-the-meeting-worth-having', 'Make this meeting worth having', 'Replace status theater with a decision, creation, or real exchange.', 'work', 'Redesign this meeting so it earns everyone''s time. State the purpose, what must happen live, what should be async, the decision owner, required preparation, agenda, and the condition for canceling it.', array['meetings','teams'], false, now()),
  ('10000000-0000-4000-8000-000000000017', 'notice-what-gives-energy', 'Notice what gives me energy', 'Use recent experience to find work that feels alive and useful.', 'reflect', 'Guide me through a brief energy audit of the last two weeks. Look for specific activities, people, environments, and kinds of difficulty that increased or drained energy. Turn the pattern into one change to my week.', array['energy','work'], false, now()),
  ('10000000-0000-4000-8000-000000000018', 'create-a-one-page-business', 'Create a one-page business', 'Connect a real customer problem to a simple path to sustainable revenue.', 'create', 'Turn this idea into a one-page business: specific customer, painful problem, current alternative, smallest valuable offer, acquisition path, price hypothesis, delivery cost, trust needed, and the next paid validation step.', array['business','revenue'], true, now()),
  ('10000000-0000-4000-8000-000000000019', 'steelman-the-other-side', 'Steelman the other side', 'Understand a disagreement before trying to win it.', 'think', 'Present the strongest good-faith version of the opposing view. Name the values and evidence behind it, where my position is weakest, what both sides may be missing, and what evidence could change either conclusion.', array['dialogue','reasoning'], false, now()),
  ('10000000-0000-4000-8000-000000000020', 'protect-a-deep-work-window', 'Protect a deep-work window', 'Design a focus block around real constraints, not ideal discipline.', 'work', 'Help me design a repeatable deep-work window around my actual schedule and interruptions. Define the task, start ritual, environment, communication boundary, stop rule, and recovery plan after a missed day.', array['focus','practice'], false, now()),
  ('10000000-0000-4000-8000-000000000021', 'write-a-respectful-no', 'Write a respectful no', 'Set a clean boundary without overexplaining or closing the relationship.', 'create', 'Draft a warm, direct refusal for the situation I describe. Keep it brief, avoid false excuses, acknowledge what matters, state the boundary clearly, and offer an alternative only if I genuinely have one.', array['communication','boundaries'], false, now()),
  ('10000000-0000-4000-8000-000000000022', 'find-the-smallest-honest-offer', 'Find the smallest honest offer', 'Charge for a useful outcome before building the whole vision.', 'create', 'Help me define the smallest offer I can sell and deliver honestly now. Identify the buyer, promised outcome, scope boundary, evidence I can provide, delivery method, fair price, and a direct invitation.', array['revenue','validation'], true, now()),
  ('10000000-0000-4000-8000-000000000023', 'plan-a-community-ritual', 'Plan a community ritual people will return to', 'Create belonging through participation, rhythm, and shared meaning.', 'create', 'Design a recurring community ritual with a clear human purpose. Include arrival, contribution, shared action, reflection, closure, accessibility, privacy expectations, and how members can shape it over time.', array['community','ritual'], false, now()),
  ('10000000-0000-4000-8000-000000000024', 'audit-for-sovereignty', 'Audit this product for human sovereignty', 'Find where a product reduces agency, obscures consent, or captures value unfairly.', 'work', 'Audit this product for human sovereignty. Examine data ownership, consent, portability, defaults, dependence, pricing, algorithmic power, community governance, and who receives the value created. Prioritize practical changes.', array['privacy','ethics'], true, now()),
  ('10000000-0000-4000-8000-000000000025', 'end-the-day-without-carrying-it', 'End the day without carrying it', 'Close open loops and leave tomorrow a kind starting point.', 'reflect', 'Lead a five-minute end-of-day reflection. Help me name what moved, what remains open, what can be released, who needs a reply, and the first kind action for tomorrow. Keep it simple and grounding.', array['ritual','reflection'], false, now())
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  prompt_text = excluded.prompt_text,
  tags = excluded.tags,
  is_featured = excluded.is_featured,
  published_at = excluded.published_at;

